version: "2"
services:
  api-database:
    image: postgres:9.6.14
    environment:
      POSTGRES_USER: server
      POSTGRES_PASSWORD: 123
    volumes:
      - database:/var/lib/postgresql/data

  api-server:
    build: .
    environment:
      # Rails Settings
      DATABASE_URL: postgres://server:123@api-database/server?pool=5
      SECRET_KEY_BASE:

      # AWS Settings
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_REGION:
      BUCKET_NAME:

      # Mailgun Settings
      MAILGUN_API_KEY:
      MAILGUN_DOMAIN:
      REDEFINE_PASSWORD_URL:
    links:
      - api-database
    volumes:
      - .:/home/app
      - /home/app/tmp
      - /home/app/log

volumes:
  database:
    driver: local
